import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Fragment_Mono
 } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaGithub, FaLinkedinIn, FaTiktok, FaWhatsapp } from "react-icons/fa";
import { SiGmail } from "react-icons/si";
import { Mail } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

const fragment_mono = Fragment_Mono({
  variable: "--font-Fragment_Mono",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${fragment_mono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-base">
        <header className="fixed z-100  flex items-center justify-between w-full h-18 py-4 backdrop-blur-3xl border-b-[0.2px] border-white/5 px-18">
          <Link href="/" scroll={true}>
            <h1 className="text-xl font-bold text-purple-700 cursor-pointer">
              Akhyr
            </h1>
          </Link>
        <nav className="">
          <ul className="flex items-center justify-center gap-4">
            <Link href="/about"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-sm rounded-2xl hover:text-primary transition-all duration-300">About</li></Link>
            <Link href="/portfolio"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">Portfolio</li></Link>
            <Link href="/projects"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">Projects</li></Link>
            <Link href="/story"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">My Story</li></Link>
            <Link href="/contact"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">Contact</li></Link>
            </ul>
        </nav>
         <button className="text-white text-sm bg-primary px-4 py-2 rounded-full hover:bg-primary/70 transition-all duration-all cursor-pointer" id="cta-button">Support Me</button>
        </header>

        <section className="mt-18">
          {children}
        </section>
        
        <header className="grid grid-cols-1 md:grid-cols-3 w-full h-auto py-4 border-t-1 border-white/5 px-18">
        {/* 1st-col */}
        <div className="flex flex-col items-start justify-start gap-4">
          <h1 className="text-xl font-bold text-purple-700 cursor-pointer">Akhyr</h1>
          <span className="text-sm text-muted">&copy; 2026 Akhyr</span>
        </div>
          
        <nav className="">
          <ul className="flex flex-col items-start justify-start gap-4">
            {/* <Link href="/portfolio"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-sm rounded-2xl hover:text-primary transition-all duration-300">About</li></Link>
            <Link href="/portfolio"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">Portfolio</li></Link>
            <Link href="projects"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">Projects</li></Link> */}
            <Link href="/story"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">My Story</li></Link>
            <Link href="/contact"><li className="text-base px-6 py-1 hover:bg-white/10 hover:filter-blur-xl rounded-2xl hover:text-primary transition-all duration-300">Contact</li></Link>
            </ul>
        </nav>
          {/* Social Media */}
          <div className="flex items-start justify-center gap-6 py-2">
            <Link href="https://www.tiktok.com/@some_._._one?_r=1&_t=ZS-95yC0x3rfwf" target="_blank">
              <FaTiktok className="hover:text-primary transition-colors duration-300 cursor-pointer" size={20} />
            </Link>
            <Link href="https://wa.me/message/RCAKWUL4WLOWF1" target="_blank">
              <FaWhatsapp className="hover:text-primary transition-colors duration-300 cursor-pointer" size={20} />
            </Link>
            <Link href="https://www.linkedin.com/in/ahmed-elkhir-43608738b?utm_source=share_via&utm_content=profile&utm_medium=member_android" target="_blank">
              <FaLinkedinIn className="hover:text-primary transition-colors duration-300 cursor-pointer" size={20} />
            </Link>
            <Link href="https://www.github.com/OCT-Ahmed" target="_blank">
              <FaGithub className="hover:text-primary transition-colors duration-300 cursor-pointer" size={20} />
            </Link>
            <Link  href="mailto:ahmedkhyr.develop@gmail.com">
              <Mail className="hover:text-primary transition-colors duration-300 cursor-pointer" size={20} />
            </Link>
            
          </div>
      </header>
      </body>
    </html>
  );
}
