import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between w-full h-18 py-4 border border-gray-600 px-18">
          <h1 className="text-xl font-bold text-purple-700">Akhyr</h1>
        <nav className="">
          <ul className="flex items-center justify-center gap-4">
            <li className="text-black-900 px-2 py-2 hover:bg-white">About</li>
            <li className="text-black px-2 py-2 hover:bg-white">Portfolio</li>
            <li className="text-black px-2 py-2 hover:bg-white">My Story</li>
            <li className="text-black px-2 py-2 hover:bg-white">My projects</li>
            <li className="text-black px-2 py-2 hover:bg-white">Contact</li>
            </ul>
        </nav>
         <button className="text-white bg-purple-600 px-4 py-2 rounded-xl cursor-pointer" id="cta-button">Support Me</button>
      </header>
        {children}
      </body>
    </html>
  );
}
